### PR TITLE
expose low level api

### PR DESCRIPTION
**Pull request by tarassh**

### CODE REVIEW

**Comment by kevaundray** [comment]
can you say why you want to expose the low level API?

**Comment by tarassh** [comment]
Hi sorry, I accidentally made a pr to original repo instead of the fork. So you can close it if you want but if you are interested in the use case and why do I need it feel free to consider:

I want to build DAS protocol similar to what Avail does with their light client approach. In nutshell light client need to pick few cells from data blob (a grid of kzg.Blobs) in order to verify if data is available. Each cell is a tuple (value, proof). So published data block has to have a proof to every value. Light client can query these tuples and verify them agains KZG commitment.

Existing implementation allows to generate a proof agains a random value but not within the polynomial domain. 
Also high level API calls have a bit of redundancy: results are serialised, and when they are passed into a next function they are deserialised. Not sure what are the benefits of serialising points and scalars all the time.

**Comment by kevaundray** [comment]
Hey no worries :) 

What you want makes complete sense. I'll be working on a new implementation that exposes this behaviour in the coming weeks. The (slight) issue with the current implementation is that it produces one proof per point being opened, whereas a "Cell", atleast how it is defined in the ethereum specs, can contain 64 opening points. 
For this, we can use a more efficient kzg proving scheme that allows one proof per 64 points without sacrificing much in terms of performance.

**Comment by tarassh** [comment]
@kevaundray can you point me to this documentation that actually might be my case as well.

**Comment by kevaundray** [comment]
> @kevaundray can you point me to this documentation, that actually might be my case as well.

Yep sure, it should all be in this document: https://github.com/ethereum/consensus-specs/blob/master/specs/_features/eip7594/polynomial-commitments-sampling.md#compute_cells_and_kzg_proofs

**Comment by kevaundray** [comment]
Going to close this as we have started to add the above functionality into the library

**Pull request closed without merging**
